[package]
name = "prooheckcp/robloxtemplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
RobloxStateMachine = "prooheckcp/robloxstatemachine@1.1.7"
RoQuest = "prooheckcp/roquest@0.1.6"